### PR TITLE
fix _BitScanReverse() usage for CE6

### PR DESCRIPTION
**Pull request by escherstair**

### CODE REVIEW

**Comment by miloyip** [comment]
I think you should just fallback to the navie version at the bottom of the function.

**Comment by escherstair** [comment]
I followed your suggestion to fallback to naive function.
But I think that the naive function needs a couple of fixes (i.e. `r` variable initialization and post-decrementing it)

**Comment by miloyip** [comment]
Would you mind adding an unit test (including the boundary cases) for this function?

**Comment by escherstair** [comment]
> 
> 
> Would you mind adding an unit test (including the boundary cases) for this function?

I can try to do my best, but I need time to understand how to use gtest.

Can you confirm that `0` is not an acceptable value for as an input to `clzll(uint64_t x)`?
I see https://github.com/Tencent/rapidjson/blob/6364c8e5ab1b9b5df01df25ff102d1c48aa0d389/include/rapidjson/internal/clzll.h#L35

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=1760) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=1760) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/rapidjson?pullRequest=1760) it.</sub>

**Comment by escherstair** [comment]
While writing the unit test I found out one important thing that must be clarified.
What is the purpose for `clzll()` function?
Counting the number of leading zeroes?
If this is the case, the original naive fallback was right, and so the https://github.com/escherstair/rapidjson/blob/58e29648561e47f6fc11ee2c2bbf8628ffc46f57/include/rapidjson/internal/clzll.h#L51
But the `_MSC_VER `implementation is not, because `_BitScanReverse()` returns the index on the first 1 (starting the search from MSB, but the index for LSB is 0).

Let me know, please

**Comment by escherstair** [comment]
I understood.
Now it should be ok

**Pull request merged**
