### PR TITLE
tests: Only run valgrind tests if valgrind was found

### PR DESCRIPTION
**Pull request by rwmjones**
valgrind is not present on all architectures (eg riscv64) and might not be installed even on supported architectures.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=2263) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=2263) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/rapidjson?pullRequest=2263) it.</sub>

**Comment by rwmjones** [comment]
@davidlt

**Comment by rwmjones** [comment]
I've asked my legal dept to review the CLA, which may take some time.

**Comment by rwmjones** [comment]
Unfortunately I'm not any closer to getting my company to review the CLA.  Would you mind merging this or a similar patch anyway, given that it is extremely trivial?

**Pull request merged**
