### PR TITLE
CMake updates

### PR DESCRIPTION
**Pull request by smancill**
Mainly, add a check to detect when the project is used as a subproject to avoid compiling/installing extra stuff by default, and avoid changing global properties. This is similar to what [fmtlib/fmt](https://github.com/fmtlib/fmt) does.

The README and the examples are still installed unconditionally though. I am inclined to add check to disable that when used as a subproject, but I am not sure what other people thinks.

There were also some issues when installing the package configuration file, so I did some fixes. The commit messages have more details.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=1454) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=1454) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/rapidjson?pullRequest=1454) it.</sub>

**Comment by smancill** [comment]
PR #1519 also shows the list of build types as options in the UI, as commit 960ff92dc6132c78dc2b455fabce21b6efe8c192 in this PR (we followed the same advice from the same blog), but I didn't want to set a default build type or consider "multiple configuration generators" in this PR, as I think it should be in its own PR.

If both PR are accepted, then there would be a merge conflict.

**Comment by mloskot** [comment]
I'm still hoping my PR #1519  is going to make it in :-)

**Comment by ClausKlein** [comment]
Why is this still open?

**Pull request closed without merging**
