### PR TITLE
Add curly braces around statement

### PR DESCRIPTION
**Pull request by AlbertHungGarmin**

### CODE REVIEW

**Comment by sembooooo** [comment]
Can I  support in this review ?

**Review by sembooooo — APPROVED** [review]
The author added curly braces properly. Looks good.

**Comment by sembooooo** [comment]
So does this mean i supported rapidJSON in any way @miloyip  ? (even if it is in the size of a water drop in a ocean)

**Comment by AlbertHungGarmin** [comment]
@miloyip , Would you take a look at this patch? The GCC ARM compiler is generating warning for 'if' statement without curly braces.

**Pull request closed without merging**
