### PR TITLE
Add test case on kParseNumbersAsStringsFlag being able to load big ints

### PR DESCRIPTION
**Pull request by lelit**
See issue #1368.

### CODE REVIEW

**Comment by miloyip** [comment]
I think it should also check whether the parsed string is as expected.

**Comment by lelit** [comment]
Ok, sure!

**Comment by lelit** [comment]
Uhm, maybe I'm missing something, but isn't that already checked by the [handler's RawNumber() method](https://github.com/Tencent/rapidjson/blob/master/test/unittest/readertest.cpp#L1888)?

**Comment by miloyip** [comment]
Oh, true.

**Pull request merged**
