### PR TITLE
Eliminate missing prototypes warning

### PR DESCRIPTION
**Pull request by AlbertHungGarmin**

### CODE REVIEW

**Comment by AlbertHungGarmin** [comment]
@miloyip, This is a small issue, clang gives missing-prototypes and gcc gives missing-declarations warning. Could you check on this?

**Comment by miloyip** [comment]
I have no idea why there is just warning. Can prefixing the function definition with `static` help?

**Comment by AlbertHungGarmin** [comment]
@miloyip, your comment was really helpful. I have uploaded some new change. Could you please take a look?

**Comment by AlbertHungGarmin** [comment]
Yes, this fix the warning.

**Comment by AlbertHungGarmin** [comment]
Yes, this fix the warning.

**Pull request merged**
