### PR TITLE
Wrap all WriteXxx() calls within EndValue()

### PR DESCRIPTION
**Pull request by lelit**
This attempts to fix issue #1336: although it seems doing the right thing, I'm not sure this is the right _fix_, as my C++ knowledge is just above 0.

Also, I tried to run the test suite, but I do not understand why I'm hitting the following:
```
$ git submodule update --init
fatal: remote error: want 0a439623f75c029912728d80cb7f1b8b48739ca4 not valid
fatal: The remote end hung up unexpectedly
Fetched in submodule path 'thirdparty/gtest', but it did not contain 0a439623f75c029912728d80cb7f1b8b48739ca4. Direct fetching of that commit failed.
```

Thank you for any advice!

### CODE REVIEW

**Comment by miloyip** [comment]
Hi. I think ideally it should test all JSON types, in order to cover all the changes.

**Comment by lelit** [comment]
Ok, will do. 

I had a doubt whether a the solution was right, or if instead it should be something different: would it be possible for example override _just_ the `Prefix()` method instead?

**Comment by miloyip** [comment]
I think the solution is right. I forgot to modify the prettywriter while fixing writer for relaxed JSON syntax in the past.

**Comment by lelit** [comment]
Ok, thank you!

**Comment by miloyip** [comment]
Thank you for your contribution.

**Comment by lelit** [comment]
Great, thank you!

**Pull request merged**
