### PR TITLE
Fix memory leak when an exception is thrown in GetRemoteDocument

### PR DESCRIPTION
**Pull request by foxtacles**
To address #818, any resources must be freed when an exception is thrown in `GetRemoteDocument`.

Any exception thrown in `GetRemoteDocument` will stop the process of resolving the schema, resources already allocated will be freed properly and the `GenericSchemaDocument` will not be constructed.

I'm not sure if this part is acceptable in the RapidJSON code base, since I've not seen any exception support like it anywhere else in the files. If it's not, I think the `GetRemoteDocument` should be made `noexcept`.

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=1402) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=1402) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/rapidjson?pullRequest=1402) it.</sub>

**Comment by ylavic** [comment]
> Any exception thrown in `GetRemoteDocument` will stop the process of resolving the schema, resources already allocated will be freed properly and the `GenericSchemaDocument` will not be constructed.
> 
> I'm not sure if this part is acceptable in the RapidJSON code base, since I've not seen any exception support like it anywhere else in the files.

The Schema code seems to replace any invalid (sub-)chema with typeless_ (an empty one), this possibly applies here too.
So I think that the try/catch should be limited to/moved around the call to GetRemoteDocument(), and that HandleRefSchema() could "return" typeless_ in case of caught exception.

FWIW, I have a branch [here](https://github.com/ylavic/rapidjson/commits/schema_syntax) which tracks and provides SchemaDocument::IsValid(), for the user to finally be able to know if something went wrong during the parsing.
Currently it's based off the branch for #1393 which is not reviewed/accepted (yet, hopefully), so I'm waiting to propose a new PR...

> If it's not, I think the `GetRemoteDocument` should still be made `noexcept` regardless.

Agreed.

**Comment by foxtacles** [comment]
It depends on what kind of behaviour you'd like to see here. I see two ways overall here:

1) Let the exception propagate, free resources and effectively halt the construction of `GenericSchemaDocument`.
2) Catch the exception, mark the sub-schema as invalid, like you proposed and which is implemented in #1415 

I think both are valid cases.

By my experience, throwing an exception usually means you want to get out of the situation and do not care about any further parsing. I have a few applications using RapidJSON which pre-load schemas, and they have thousands of `$ref`'s combined. If just one if missing, the application is not going to work and I want to cleanly halt execution. I don't want any other `$ref` to be processed because that's a waste of time and resources. This PR allows to do this.

I think we could actually enable both. We could come to an agreement that if you'd like to see 2), you are supposed to return a `nullptr` from `GetRemoteDocument`, which will mark the sub-schema as invalid and with #1415 you can later inspect this.

I've looked at your PR's and I hope they'll get merged. Then, I'll have to adjust the contents here anyway because there are some conflicts. I'd love to hear @miloyip feedback on this topic.

**Comment by ylavic** [comment]
If 1. needs to be implemented, I'm not sure catching exceptions in `SchemaDocument` helps. For instance if an exception is raised from `GetRemoteDocument` it seems to me that it should be caught/handled by the caller appropriately. IOW nothing seems to be needed in Rapidjson itself.

For the parsing to be interrupted (on error), Rapidjson should `throw` somehow (more than `catch`), probably where #1415 handles valid_ = false...
Something like `RAPIDJSON_PARSE_ERROR_NORETURN` in `GenericDocument`, the user would be responsible for setting `RAPIDJSON_PARSE_SCHEMA_ERROR_NORETURN` and catching the exception.
If not set, the question is should the parsing continue (as currenly) or should the same "early return" stragegy as `GenericDocument` be implemented? Probably another user's choice...

**Comment by foxtacles** [comment]
> If 1. needs to be implemented, I'm not sure catching exceptions in `SchemaDocument` helps. For instance if an exception is raised from `GetRemoteDocument` it seems to me that it should be caught/handled by the caller appropriately. IOW nothing seems to be needed in Rapidjson itself.

I think RapidJSON must catch any exception being thrown, otherwise it's possible that memory will be leaked, like shown in the example of #818 - or am I missing something? It should `catch (...)`, release memory and then re-throw. That's what this PR does.

**Comment by ylavic** [comment]
Stack unwinding pattern can also be used, like in `GenericDocument`'s `ClearStackOnExit`, to address leaks on exception.

**Comment by foxtacles** [comment]
Ah! Well, as long as we have a solution to #818 and ideally a mechanism for early termination of schema processing on error, I'll be content.

**Comment by ylavic** [comment]
Possibly something like [this](https://github.com/ylavic/rapidjson/commits/schema_unwinding) branch would work...

**Comment by foxtacles** [comment]
Yeah, I like that better than what I did, especially since it'll be consistent with the rest of RJ. If you don't mind I'll take that implementation of yours and use it instead. I think we need to use the same pattern in the `Schema` class as well. I'm going to wait until we hear from @miloyip and then come up with a new solution.

**Comment by foxtacles** [comment]
@ylavic the  `Schema` constructor creates sub-schemas with `CreateSchema` (which is using `GetRemoteDocument`) so the same pattern needs to applied I think. I had the unit test run without it and it detected the leak.

I've changed the implementation so the stack unwinding pattern is now used in both constructors. There's still one `try...catch` block left which needs to stay to avoid a leak. There might be other cases like it within `Schema`, I still need to check it.

Would appreciate any comments/hints and I'm looking forward to getting the original issue resolved soon.

**Comment by ylavic** [comment]
Anyway, I something were to be done at the `SchemaDocument` level, a scoped:
```
try {
    remoteDocument = remoteProvider_->GetRemoteDocument(s, i);
}
catch (...) {
    remoteDocument = 0;
}
```
is probably the best option.

**Comment by ylavic** [comment]
> Given the discussion in #1415, I think failing early on schema parsing is not really relevant anymore since schemas are considered valid in the first place (the same applies to remote schemas I guess).

Well, I'm not that sure actually. Remote documents can fail regardless of their syntax (e.g. network error...). So handling exceptions for them may be an option.

**Comment by foxtacles** [comment]
> Well, I'm not that sure actually. Remote documents can fail regardless of their syntax (e.g. network error...). So throwing exceptions for them may be an/the only option.

Yeah, that's what I thought as well. I read the discussion in #1415 but I think having to make sure all remote $refs will be present and valid before launching a validation is quite a burden on client code

**Comment by ylavic** [comment]
On the other hand, `remoteProvider_` can track failures and return NULL, the user can then check that after the `SchemaDocument` is parsed. Throwing an exception is just an optimization to fail fast right?

**Comment by foxtacles** [comment]
yep

**Pull request closed without merging**
