### PR TITLE
Fix strtod

### LINKED ISSUE #849: Inconsistent reporting of numbers that are too big to be stored in a double
If a JSON document contains a floating-point number that is too big to be stored in a double, RapidJSON sometimes raises an error that says "Number too big to be stored in double", and other times it silently accepts it and returns positive or negative infinity. It would be better if it consistently reported an error when it encountered a number that was too big.

Take this test program:

```c++
#include <iostream>
#include "rapidjson/error/en.h"
#include "rapidjson/error/error.h"
#include <rapidjson/reader.h>
#include <rapidjson/stream.h>

using namespace rapidjson;

class Handler : public BaseReaderHandler<UTF8<> > {
public:
  bool Double(double d) {
    std::cout << d;
    return true;
  }
};

void test(const char* json) {
  std::cout << json << " -> ";
  Reader reader;
  StringStream stream(json);
  Handler handler;
  if (!reader.Parse(stream, handler)) {
    std::cout << GetParseError_En(reader.GetParseErrorCode());
  }
  std::cout << std::endl;
}

int main() {
  test("3.14");
  test("1e308");
  test("1.7e308");
  test("1.8e308");
  test("5e308");
  test("1e309");
  test("1.0e310");
  test("1.00e310");
  test("-1.7e308");
  test("-1.8e308");
  test("-1e309");
}
```

With g++ 6.3.0 on Debian 9 (amd64), I see the following output:

```
3.14 -> 3.14
1e308 -> 1e+308
1.7e308 -> 1.7e+308
1.8e308 -> inf
5e308 -> inf
1e309 -> Number too big to be stored in double.
1.0e310 -> Number too big to be stored in double.
1.00e310 -> inf
-1.7e308 -> -1.7e+308
-1.8e308 -> -inf
-1e309 -> Number too big to be stored in double.
```

It would be more consistent if those cases that currently say "inf" or "-inf" said "Number too big" instead.

### PR DESCRIPTION
**Pull request by abolz**
Fixes #849, #1249, #1251, #1253, #1256, #1259

The issues were mainly because of unsigned integer overflow and boundary cases. Switched to signed integer arithmetic.

To do:
* This patch currently requires "small inputs" and "small exponents" due to integer overflow. Fixing this probably requires some more changes in `ParseNumber`. (Or simply using int64 instead of int32)
* Some inaccuracies in full-precision mode (due to discarding non-zero bits) should be fixed.

### CODE REVIEW

**Comment by miloyip** [comment]
Really thank for your contribution.
There is some valgrind errors such as https://travis-ci.org/Tencent/rapidjson/jobs/392709049#L2555 Can you take a look?

**Comment by abolz** [comment]
Yes, looking into it. But honestly I have no idea whats wrong... Valgrind complains about an uninitialized variable of size 4 in StrtodBigInteger.

**Comment by abolz** [comment]
BTW could you cancel all the running appveyor builds?

**Comment by abolz** [comment]
The valgrind error is fixed now (was due to an incorrect offset computation in BigInteger operator<<).
There are still some tests for edge cases in full-precision mode failing, which need to be fixed.

**Pull request merged**
