### PR TITLE
Issue 1924 - stop erroneous compiler warnings

### PR DESCRIPTION
**Pull request by smhdfdl**
Fixes the problem described by issue #1924, by refactoring the code slightly so the compiler does not get confused..

### CODE REVIEW

**Comment by smhdfdl** [comment]
@miloyip please can you review this PR?

**Comment by miloyip** [comment]
No files changes?

**Comment by smhdfdl** [comment]
@miloyip Apologies - forgot to commit the change - it was late :)

**Comment by miloyip** [comment]
Thanks

**Pull request merged**
