### PR TITLE
Fix ARM NEON under MSVC

### LINKED ISSUE #1521: ARM64 builds fails if Neon is enabled on MSVC
When building rapidjson for ARM64 with RAPIDJSON_NEON defined on MSVC, it will fail to build, because it includes `<arm_neon.h>`, but this is for ARM 32-bits only on Microsoft's compiler. The right file to include is `<arm64_neon.h>`

Apparently a fix is incoming, but this was posted in April and we're in June now... https://developercommunity.visualstudio.com/content/problem/201662/arm-neonh-doenst-support-arm64-compiler.html

### PR DESCRIPTION
**Pull request by sylveon**
Fixes #1521

### CODE REVIEW

**Comment by tencent-adm** [comment]
[CLA assistant check](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=1548) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.tencent.com/Tencent/rapidjson?pullRequest=1548) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.tencent.com/check/Tencent/rapidjson?pullRequest=1548) it.</sub>

**Comment by sylveon** [comment]
Is it possible to get attention on this? Without this PR it's not possible at all to build RapidJSON on Windows ARM with NEON enabled

**Comment by sylveon** [comment]
@miloyip Could this get reviewed and merged?

**Comment by miloyip** [comment]
Thank you

**Pull request merged**
